global:
    scrape_interval: 15s

scrape_configs:
    - job_name: "shopdev-go-api"
      scrape_interval: 5s
      static_configs:
        - targets: ["host.docker.internal:8002"]

    - job_name: "shopdev-go-prometheus"
      scrape_interval: 5s
      static_configs:
        - targets: ["host.docker.internal:9092"]
     