server:
  port: 8082
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10   #số lượng kết nối tối đa được giữ trong pool
  maxOpenConns: 100  #số lượng kết nối tối đa mở cùng một lúc
  connMaxLifetime: 3600 # thời gian tối đa một kết nối được giữ trong pool
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
redis:
  host: 127.0.0.1
  port: 6381
  password: 
  database: 0